interface DemirHayatCreateProposalType {
    branchId: string,
    productId: string,
    productTarifId: string,
    productVersionId: string,
    paymentPlanId: string,
    paymentTypeId: string,
    startDate: string,
    ownerIdNumber: string,
    ownerNationalityId: string,
    ownerPassportNumber: string,
    ownerTaxNumber: null | string,
    ownerTaxOffice: null | string,
    ownerTypeId: string,
    ownerName: string,
    ownerSurname: string,
    ownerFatherName: string,
    ownerBirthDate: string,
    ownerGenderId: string,
    ownerAddress: string,
    ownerDistrictId: string,
    ownerCityId: string,
    ownerPhone: string,
    ownerGsm: string,
    ownerEmail: string,
    ownerProfessionId: string,
    ownerBirthPlace: string,
}


export default DemirHayatCreateProposalType